### ISSUE TITLE
只能在局域网内使用，远程网PIng不通

### ISSUE THREAD

**Issue by fzlychee2019** [Safe3/fahi#10]
局域网内机器可以ping得通，但是远程电脑间都无法ping通，无法使用。难道还有啥防火墙设置需要单独设置？LINUX和WINDOWS系统，远程都无法联通

**Comment by Safe3** [comment]
你两边客户端关闭再开启下试试，应该现在可以了，今天上午有部分服务出现故障，现已恢复！
