### ISSUE TITLE
不开源吗

### ISSUE THREAD

**Issue by 13653216371** [Safe3/fahi#9]
这种软件不开源不可能有人用的

**Comment by xuemian168** [comment]
headscale+derp模式 怎么开源 服务为主

**Comment by Safe3** [comment]
法海和headscale、tailscale没半点关系，不开源的原因是怕被非法利用

**Comment by 13653216371** [comment]
> headscale+derp模式 怎么开源 服务为主

实际上headscale和derp都是开源的

**Comment by xuemian168** [comment]
> 法海和headscale、tailscale没半点关系，不开源的原因是怕被非法利用

行 那是我肤浅了
